# -*- coding: utf-8 -*-
"""hexedecimal_metindönüstücü.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdF_edSAKPCRve5PjYum0-21cO206lzW
"""

def metin_to_hex(metin):
    hex_sonuc = metin.encode("utf-8").hex()
    return hex_sonuc

def hex_to_metin(hex_metin):
    metin = bytes.fromhex(hex_metin).decode("utf-8")
    return metin

while True:
    print("\nHexadecimal Metin Oluşturucu")
    print("1. Metni Hex'e çevir")
    print("2. Hex'i metne çevir")
    print("3. Çıkış")
    secim = input("Seçiminizi yapın: ")

    if secim == "1":
        metin = input("Metni girin: ")
        print("Hexadecimal karşılığı:", metin_to_hex(metin))
    elif secim == "2":
        hex_metin = input("Hexadecimal metni girin: ")
        try:
            print("Metin karşılığı:", hex_to_metin(hex_metin))
        except:
            print("Geçersiz hexadecimal metin!")
    elif secim == "3":
        print("Programdan çıkılıyor...")
        break
    else:
        print("Geçersiz seçim, tekrar deneyin!")